baseURL = 'http://leif.io/'
languageCode = 'en-us'
title = 'Leif Thoughts'
defaultContentLanguage = 'en'
copyright = 'Leif Gensert'
pluralizelisttitles = false

[author]
name = 'Leif Gensert'
image = 'img/avatar.jpg'
links = [
  { twitter = "https://twitter.com/leifg" },
  { facebook = "https://facebook.com/lgensert" },
  { linkedin = "https://linkedin.com/in/lgensert" },
  { instagram = "https://instagram/leifg" },
]

[permalinks]
posts = '/blog/:year/:month/:day/:slug/'

[taxonomies]
blog = 'blog'
