baseURL: 'https://leif.io/'
languageCode: en-us
defaultContentLanguage: en
enableRobotsTXT: false
pluralizelisttitles: false
permalinks:
  posts: '/blog/:year/:month/:day/:slug/'
taxonomies:
  blog: blog
outputs:
  home:
    - HTML
    - RSS
    - JSON
