baseURL: 'https://leif.io/'
languageCode: en-us
defaultContentLanguage: en
enableRobotsTXT: false
pluralizelisttitles: false
permalinks:
  page:
    posts: '/blog/:year/:month/:day/:slug/'
timeout: 300s
outputs:
  home:
    - HTML
    - RSS
    - JSON
