colorScheme: ocean
autoSwitchAppearance: true
showAppearanceSwitcher: true
homepage:
  layout: profile
list:
  showSummary: false
fathomAnalytics:
  site: OORKIHUO
  domain: day-life-legendary.leif.io
enableSearch: true
